theme = "peachpuff"

[keys.normal]
C-s = ":w"
# C-o = ":open ~/.config/helix/config.toml"
C-l = ":open ~/.config/helix/languages.toml"
H = "goto_line_start"
L = "goto_line_end"
C-q = ":q"

[keys.insert]
C-s = ":w"

[editor.cursor-shape]
insert = "bar"
select = "underline"
